- name:
  hosts: web
  roles:
  - web
  # vars:
  #   package: nginx
  #   my_message: Hello From NTIii
  #   files_list:
  #   - file.css
  #   - file.js
  # tasks:
  # - name:
  #   apt:
  #     name: "{{package}}"
  #     state: latest
  #   notify: my_handler
  #   changed_when: true
  # - name: my template
    # template: 
    #   src: ./index.html.j2
    #   dest: /var/www/html/index.html
    # changed_when: true
    # notify: my_handler2
  # handlers:
  # - name: my_handler
  #   copy:
  #     src: "./{{item}}"
  #     dest: "/home/ansible/{{item}}"
  #   loop:
  #   - file.css
  #   - file.js
  #   changed_when: true
  #   notify: my_handler2
  # - name: my_handler2
  #   sysvinit:
  #     name: "{{package}}"
  #     state: restarted  
